// react/src/App.tsx
import YeForm from "@/components/YeForm.tsx";
import { Email, example } from "@yoe-form/shared";

function App() {
  const handleEmail = async (
    _values: Record<string, unknown>,
    _internalEmail: Email,
    confirmationEmail?: Email,
  ) => {
    alert(confirmationEmail);
  };

  const handleRestCall = async (
    url: string,
    values: Record<string, unknown>,
  ) => {
    alert(JSON.stringify({ url, ...values }));
  };

  return (
    <div className="flex h-full w-full justify-center">
      <div className="flex w-1/2 flex-col items-center justify-center">
        <h1 className="text-5xl">React</h1>
        <YeForm
          config={example}
          emailHandler={handleEmail}
          restHandler={handleRestCall}
          language={"de"}
          className="ye-date:text-sm"
        />
      </div>
    </div>
  );
}

export default App;

// nuxt/src/App.vue
<script setup lang="ts">
import { Email, example } from "@yoe-form/shared";
import YeForm from "@/components/YeForm.vue";

const handleEmail = async (
  _values: any,
  _internalEmail: Email,
  confirmationEmail?: Email,
) => {
  alert(JSON.stringify(confirmationEmail));
};

const handleRestCall = async (url: string, values: any) => {
  alert(JSON.stringify({ url, ...values }));
};
</script>

<template>
  <div class="flex justify-center w-full h-full">
    <div class="flex flex-col items-center justify-center w-1/2">
      <h1 class="text-5xl">Nuxt</h1>
      <YeForm
        :config="example"
        :emailHandler="handleEmail"
        :restHandler="handleRestCall"
        language="de"
        class="ye-radio-checked:bg-slate-50"
      />
    </div>
  </div>
</template>
