// nuxt/src/components/YeFormCustom.vue
<script setup lang="ts">
import { useForm } from "vee-validate";
import { setLocale } from "yup";
import { type Component } from "vue";
import { Button } from "@/components/ui/button";
import {
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { vAutoAnimate } from "@formkit/auto-animate/vue";
import {
  buildEmails,
  buildFormSchema,
  EmailHandler,
  errorTranslations,
  getGridClasses,
  getTranslation,
  Language,
  RestHandler,
  YeFormConfig,
} from "@yoe-form/shared";
import { cn } from "@/lib/utils.ts";

export interface YeFormProps {
  config: YeFormConfig;
  emailHandler?: EmailHandler;
  restHandler?: RestHandler;
  language?: Language;
  button: Component;
  dynamicInput: Component;
}

const { config, emailHandler, restHandler, language } =
  defineProps<YeFormProps>();
const {
  rows,
  emailConfig,
  restEndpoint,
  buttonText,
  submissionMethod,
  disableLabels,
  disableRequiredStars,
} = config;

// translate error messages
if (language && language !== "en") {
  setLocale(errorTranslations[language]);
}

const form = useForm({
  validationSchema: buildFormSchema(rows),
});

const onSubmit = form.handleSubmit(async (values) => {
  if (submissionMethod === "email" && emailConfig && emailHandler) {
    const { internalEmail, confirmationEmail } = buildEmails(
      emailConfig,
      values,
      language,
    );
    return emailHandler(values, internalEmail, confirmationEmail);
  } else if (submissionMethod === "rest" && restEndpoint && restHandler) {
    return restHandler(values, restEndpoint);
  }
});
</script>

<template>
  <form
    :class="cn('my-4 space-y-4', $attrs.class ?? '')"
    @submit.prevent="onSubmit"
  >
    <div
      v-for="(row, index) in rows"
      :key="index"
      class="grid grid-cols-3 gap-4 md:grid-cols-6"
    >
      <div
        v-for="(field, index) in row.fields"
        :key="index"
        :class="getGridClasses(field.layout)"
      >
        <FormField
          v-slot="{ componentField, value, handleChange }"
          :name="field.name"
          :type="field.type"
        >
          <FormItem v-auto-animate data-ye-element="item">
            <div class="flex items-center gap-4">
              <FormLabel v-if="!disableLabels" data-ye-element="label"
                >{{ getTranslation(field.label, language) }}
                <span
                  v-if="field.required && !disableRequiredStars"
                  class="text-red-500"
                  >*</span
                >
              </FormLabel>
              <div v-if="field.tooltip">
                <TooltipProvider :delay-duration="50">
                  <Tooltip>
                    <TooltipTrigger as-child>
                      <Button
                        variant="outline"
                        size="xs"
                        class="cursor-default rounded-full bg-slate-200"
                        @click.prevent
                        >?</Button
                      >
                    </TooltipTrigger>
                    <TooltipContent>
                      <p>{{ getTranslation(field.tooltip, language) }}</p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
              </div>
            </div>
            <component
              :is="dynamicInput"
              :field="field"
              :language="language"
              :componentField="componentField"
              :value="value"
              :handleChange="handleChange"
            />
            <FormMessage data-ye-element="error" />
          </FormItem>
        </FormField>
      </div>
    </div>
    <component :is="button" type="submit" data-ye-element="button">
      {{ getTranslation(buttonText, language) }}
    </component>
  </form>
</template>

// react/src/components/YeFormCustom.tsx
import { yupResolver } from "@hookform/resolvers/yup";
import { useForm } from "react-hook-form";
import { Button } from "@/components/ui/button";
import {
  Form,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { setLocale } from "yup";
import type { FC } from "react";
import {
  buildDefaultValues,
  buildEmails,
  buildFormSchema,
  errorTranslations,
  type FormValues,
  getGridClasses,
  getTranslation,
} from "@yoe-form/shared";
import { cn } from "@/lib/utils.ts";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip.tsx";
import { YeFormCustomProps } from "./YeForm.types.ts";

const YeForm: FC<YeFormCustomProps> = ({
  className,
  config,
  emailHandler,
  restHandler,
  language = "de",
  button,
  dynamicInput,
}) => {
  // set error language
  if (language && language !== "en") {
    setLocale(errorTranslations[language]);
  }

  const formSchema = buildFormSchema(config.rows);
  // Since FormField is using a controlled component, we need to provide a default value for all fields.
  const defaultValues = buildDefaultValues(config.rows);

  const form = useForm<FormValues>({
    resolver: yupResolver(formSchema),
    defaultValues,
  });

  const onSubmit = form.handleSubmit(async (values) => {
    if (
      config.submissionMethod === "email" &&
      config.emailConfig &&
      emailHandler
    ) {
      const { internalEmail, confirmationEmail } = buildEmails(
        config.emailConfig,
        values,
        language,
      );
      return emailHandler(values, internalEmail, confirmationEmail);
    } else if (
      config.submissionMethod === "rest" &&
      config.restEndpoint &&
      restHandler
    ) {
      return restHandler(values, config.restEndpoint);
    }
  });
  const ButtonComponent = button;
  const DynamicInputComponent = dynamicInput;

  return (
    <Form {...form}>
      <form
        onSubmit={onSubmit}
        className={cn("my-4 space-y-4", className ?? "")}
      >
        {config.rows.map((row, index) => (
          <div key={index} className="grid grid-cols-6 gap-4">
            {row.fields.map((yeField, index) => (
              <div key={index} className={getGridClasses(yeField.layout)}>
                <FormField
                  control={form.control}
                  name={yeField.name}
                  render={({ field }) => (
                    <FormItem data-ye-element="item">
                      <div className="flex items-center gap-4">
                        {!config.disableLabels && (
                          <FormLabel data-ye-element="label">
                            {getTranslation(yeField.label, language)}
                            {!config.disableRequiredStars &&
                              yeField.required && (
                                <span className="text-red-500"> *</span>
                              )}
                          </FormLabel>
                        )}
                        {yeField.tooltip && (
                          <TooltipProvider delayDuration={50}>
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <Button
                                  variant="outline"
                                  size="xs"
                                  className="cursor-default rounded-full bg-slate-200"
                                  onClick={(e) => e.preventDefault()}
                                >
                                  ?
                                </Button>
                              </TooltipTrigger>
                              <TooltipContent>
                                <p>
                                  {getTranslation(yeField.tooltip, language)}
                                </p>
                              </TooltipContent>
                            </Tooltip>
                          </TooltipProvider>
                        )}
                      </div>
                      <DynamicInputComponent
                        fieldConfig={yeField}
                        language={language}
                        field={field}
                      />
                      <FormMessage data-ye-element="error" />
                    </FormItem>
                  )}
                />
              </div>
            ))}
          </div>
        ))}
        <ButtonComponent type="submit" data-ye-element="button">
          {getTranslation(config.buttonText, language)}
        </ButtonComponent>
      </form>
    </Form>
  );
};

export default YeForm;
